/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'app.release+HE' 
 * Target:  'release+HE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HE.h"

/* ARM::RTOS&FreeRTOS:Config&FreeRTOS@11.1.0 */
#define RTE_RTOS_FreeRTOS_CONFIG        /* RTOS FreeRTOS Config for FreeRTOS API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.1.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.1.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.1.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.1.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* AlifSemiconductor::BSP:External peripherals:ILI9806E LCD panel@1.3.0 */
#define RTE_Drivers_MIPI_DSI_ILI9806E_PANEL 1   /* Driver ILI9806E LCD panel*/
/* AlifSemiconductor::Device:SOC Peripherals:CDC@1.3.0 */
#define RTE_Drivers_CDC200 1   /* Driver CDC200*/
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI CSI2 DPHY@1.3.0 */
#define RTE_Drivers_MIPI_DSI_CSI2_DPHY   1   /* Driver DPHY */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI@1.3.0 */
#define RTE_Drivers_MIPI_DSI   1   /* Driver MIPI DSI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:USART@1.3.0 */
#define RTE_Drivers_USART0   1           /* Driver UART0 */
#define RTE_Drivers_USART1   1           /* Driver UART1 */
#define RTE_Drivers_USART2   1           /* Driver UART2 */
#define RTE_Drivers_USART3   1           /* Driver UART3 */
#define RTE_Drivers_USART4   1           /* Driver UART4 */
#define RTE_Drivers_USART5   1           /* Driver UART5 */
#define RTE_Drivers_USART6   1           /* Driver UART6 */
#define RTE_Drivers_USART7   1           /* Driver UART7 */
/* AlifSemiconductor::Graphics:Acceleration:GPU AlifSemi-Dave2D@1.0.0 */
/*! \brief enable Dave2D */
#define LV_USE_DRAW_DAVE2D  1
/* LVGL::LVGL&LVGL9:Demos:Benchmark@9.1.0 */
/*! \brief enable demo:bencharmk */
#define LV_USE_DEMO_BENCHMARK           1
/* LVGL::LVGL&LVGL9:Demos:Widgets@9.1.0 */
/*! \brief enable demo:widgets support */
#define LV_USE_DEMO_WIDGETS             1
/* LVGL::LVGL&LVGL9:Essential@9.1.0 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL
/* LVGL::LVGL&LVGL9:OS Abstraction Layer&FreeRTOS@9.1.0 */
/*   Select an operating system to use. Possible options:
* - LV_OS_NONE
* - LV_OS_PTHREAD
* - LV_OS_FREERTOS
* - LV_OS_CMSIS_RTOS2
* - LV_OS_RTTHREAD
* - LV_OS_WINDOWS
* - LV_OS_CUSTOM
*/
#define LV_USE_OS   LV_OS_FREERTOS


#endif /* RTE_COMPONENTS_H */
